CREATE TABLE ECUACION_CUBICA_O(
ID NUMBER GENERATED ALWAYS AS IDENTITY,
A NUMBER,
B NUMBER,
C NUMBER,
D NUMBER,
ECUACION VARCHAR2(300),
RAICES VARCHAR2(300),
FECHA DATE DEFAULT SYSDATE,
PRIMARY KEY(ID)
);

COMMIT;

CREATE TABLE PUNTOS_GRAFICA(
ID NUMBER GENERATED ALWAYS AS IDENTITY,
ID_ECUACION NUMBER,
X NUMBER,
Y NUMBER,
PRIMARY KEY(ID),
FOREIGN KEY(ID_ECUACION)
REFERENCES ECUACION_CUBICA(ID)
);

COMMIT;